/**
 * Shared Node-side helpers for running SMA sweeps against real DB-backed price
 * data outside the browser. Extracted from generate-snapshots.ts so
 * calibrate-sma.ts can reuse the exact same data loading + sweep execution
 * path without duplicating it.
 */

import { readFileSync } from "node:fs";
import { join } from "node:path";
import { getBorrowRate, getPriceDateBounds, getPrices } from "../../src/lib/db/queries";
import type { EtfConfig, PricePoint, RatePoint, RiskOffAsset } from "../../src/lib/simulation/types";
import { precomputeAllConfigDailyValues, buildSimulationBuckets } from "../../src/lib/simulation/parallel";
import type { RollingSimulationPoint, RollingWindow } from "../../src/lib/simulation/rolling";
import { annualizedInflationForRange } from "../../src/lib/inflation";
import { alignCloseSeriesToDates, alignOpenSeriesToDates } from "../../src/lib/utils";

export type MonthlyCpiPoint = { date: string; value: number };

const SMA_WARMUP_BUFFER_TRADING_DAYS = 20;
const TRADING_DAYS_PER_YEAR = 250;

export async function loadPrices(index: string, startDate: string, endDate: string): Promise<PricePoint[]> {
  const rows = await getPrices(index, startDate, endDate);
  return rows
    .filter((row) => {
      const adjClose = row.adj_close ?? Number.NaN;
      return Number.isFinite(adjClose) && adjClose > 0;
    })
    .map((row) => ({
      date: row.date,
      adj_open: row.adj_open,
      adj_close: row.adj_close as number,
      open: row.open,
      close: row.close ?? (row.adj_close as number),
    }));
}

export async function loadRates(startDate: string, endDate: string): Promise<RatePoint[]> {
  const rows = await getBorrowRate(startDate, endDate);
  return rows.map((row) => ({
    date: row.date,
    rateType: "borrow",
    rateValue: row.value,
  }));
}

export function getUniquePrimitiveRiskOffAssets(assets: RiskOffAsset[]): RiskOffAsset[] {
  const out = new Set<RiskOffAsset>();
  for (const asset of assets) {
    if (asset.includes("+")) {
      for (const part of asset.split("+")) out.add(part as RiskOffAsset);
    } else {
      out.add(asset);
    }
  }
  return [...out];
}

export async function loadRiskOffValuesForReference(
  primitiveAssets: RiskOffAsset[],
  referencePrices: PricePoint[],
  startDate: string,
  endDate: string
): Promise<{
  closeValuesByAsset: Partial<Record<RiskOffAsset, number[]>>;
  openValuesByAsset: Partial<Record<RiskOffAsset, number[]>>;
}> {
  const closeValuesByAsset: Partial<Record<RiskOffAsset, number[]>> = {};
  const openValuesByAsset: Partial<Record<RiskOffAsset, number[]>> = {};
  for (const asset of primitiveAssets) {
    const storageKey =
      asset === "VOO"
        ? "sp500"
        : asset === "QQQ"
          ? "nasdaq100"
          : asset === "BRK.B"
            ? "risk:BRKA"
            : `risk:${asset.replace(".", "")}`;
    const points = await loadPrices(storageKey, startDate, endDate);
    closeValuesByAsset[asset] = alignCloseSeriesToDates(referencePrices, points);
    openValuesByAsset[asset] = alignOpenSeriesToDates(referencePrices, points);
  }
  return { closeValuesByAsset, openValuesByAsset };
}

export async function fetchInflationData(startDate: string, endDate: string): Promise<{
  annualizedInflation: number;
  monthlyCpi: MonthlyCpiPoint[];
}> {
  // Read from inflation.csv (generated by fetch-data) instead of calling FRED API.
  // Uses process.cwd() (not __dirname) so this works from any script location —
  // both generate-snapshots.ts and calibrate-sma.ts always run via `npm run ...`
  // from the repo root.
  const csvPath = join(process.cwd(), "data", "inflation.csv");
  let raw: string;
  try {
    raw = readFileSync(csvPath, "utf-8");
  } catch {
    console.warn("[sweep-data] inflation.csv not found; inflation-dependent metrics will fall back to 0.");
    return { annualizedInflation: 0, monthlyCpi: [] };
  }

  const lines = raw.trim().split("\n");
  const allObservations: MonthlyCpiPoint[] = [];
  for (let i = 1; i < lines.length; i++) {
    const cols = lines[i].split(",");
    if (cols.length < 2) continue;
    const dateStr = cols[0];
    const value = Number(cols[1]);
    if (!dateStr || !isFinite(value)) continue;
    const normalized = dateStr.length === 7 ? `${dateStr}-01` : dateStr;
    allObservations.push({ date: normalized, value });
  }
  allObservations.sort((a, b) => a.date.localeCompare(b.date));

  // Filter to range: include observations from 2 months before startDate
  const rangeStartDate = new Date(`${startDate}T00:00:00Z`);
  rangeStartDate.setUTCMonth(rangeStartDate.getUTCMonth() - 2);
  const rangeStart = rangeStartDate.toISOString().slice(0, 10);

  const monthlyCpi = allObservations.filter(
    (o) => o.date >= rangeStart && o.date <= endDate
  );

  return {
    annualizedInflation: annualizedInflationForRange(monthlyCpi, startDate, endDate),
    monthlyCpi,
  };
}

/**
 * Precompute daily values for multiple configs, then slice rolling windows for each.
 * Used by sweep functions where many configs share the same price/rate data.
 */
export function runPrecomputedSweep({
  prices,
  rates,
  configs,
  windows,
  riskOffValuesByAsset,
  riskOffOpenValuesByAsset,
}: {
  prices: PricePoint[];
  rates: RatePoint[];
  configs: EtfConfig[];
  windows: RollingWindow[];
  riskOffValuesByAsset?: Partial<Record<RiskOffAsset, number[]>>;
  riskOffOpenValuesByAsset?: Partial<Record<RiskOffAsset, number[]>>;
}): Map<string, RollingSimulationPoint[]> {
  const precomputed = precomputeAllConfigDailyValues(
    prices,
    rates,
    configs,
    riskOffValuesByAsset,
    riskOffOpenValuesByAsset
  );
  const buckets = buildSimulationBuckets(precomputed, windows, prices, {
    rates,
    configs,
    riskOffValuesByAsset,
    riskOffOpenValuesByAsset,
  });
  const result = new Map<string, RollingSimulationPoint[]>();
  for (const bucket of buckets) {
    result.set(bucket.configId, bucket.simulations);
  }
  return result;
}

function shiftIsoDateByDays(isoDate: string, days: number): string {
  const d = new Date(`${isoDate}T00:00:00Z`);
  d.setUTCDate(d.getUTCDate() + days);
  return d.toISOString().slice(0, 10);
}

export function getSmaWarmupStartDate(startDate: string, maxSmaPeriod: number): string {
  if (maxSmaPeriod <= 0) return startDate;
  const warmupCalendarDays = Math.ceil(
    ((maxSmaPeriod + SMA_WARMUP_BUFFER_TRADING_DAYS) * 365.25) / TRADING_DAYS_PER_YEAR
  );
  return shiftIsoDateByDays(startDate, -warmupCalendarDays);
}

/** Latest date for which every one of the given price keys has data. */
export async function getLatestSharedTradeDate(priceKeys: string[]): Promise<string> {
  const bounds = await Promise.all(priceKeys.map((key) => getPriceDateBounds(key)));

  const maxDates = bounds.map((b, i) => {
    if (!b?.maxDate) {
      throw new Error(`Missing price data for ${priceKeys[i]}`);
    }
    return b.maxDate;
  });

  return maxDates.reduce((min, current) => (current < min ? current : min));
}
