/**
 * Generate canned default tool snapshots from the current database state.
 *
 * Usage:
 *   npx tsx scripts/generate-snapshots.ts
 *   npx tsx scripts/generate-snapshots.ts --page compare-letfs
 *   npx tsx scripts/generate-snapshots.ts --page all
 *   npm run snapshots:generate
 *
 * Notes:
 *   - Uses the latest shared trade date already present in the local DB.
 *   - Reads CPI data from data/inflation.csv (generated by fetch-data).
 *   - Writes per-page JSON files to src/lib/tool-snapshots/.
 */

/* eslint-disable @typescript-eslint/no-unused-vars */

import { config } from "dotenv";
config({ path: ".env.local" });

import { existsSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  fetchInflationData,
  getLatestSharedTradeDate,
  getSmaWarmupStartDate,
  getUniquePrimitiveRiskOffAssets,
  loadPrices,
  loadRates,
  loadRiskOffValuesForReference,
  runPrecomputedSweep,
  type MonthlyCpiPoint,
} from "./lib/sweep-data";
import {
  CHART_COLORS,
  CONSTANT_INITIAL_INVESTMENT,
  CONSTANT_SP500_SHORTCUT_DATE,
  LABEL_INDEX_NASDAQ100_TR,
  LABEL_INDEX_SP500_TR,
  RISK_OFF_ASSET_OPTIONS,
  getRiskOffFetchTickers,
} from "../src/lib/constants";
import type {
  BacktestResult,
  EtfConfig,
  EtfResult,
  IndexKey,
  ParallelBacktestResult,
  PricePoint,
  RatePoint,
  RiskOffAsset,
  SmaComparisonRow,
} from "../src/lib/simulation/types";
import {
  DEFAULT_FUTURES_AMOUNT,
  DEFAULT_LEVERAGE_TOLERANCE_PCT,
  DEFAULT_RISK_OFF_ASSET,
  getDefaultSmaBuffer,
  getDefaultSmaPeriod,
  getDefaultWindowLength,
} from "../src/lib/simulation/defaults";
import {
  DEFAULT_COMBO_PRESET,
  ETF_PRESETS,
  createPresetEtfConfig,
  getComboSubPresets,
} from "../src/lib/simulation/presets";
import {
  buildRollingWindows,
  summarizeParallelResult,
  summarizeSmaRow,
  type RollingSimulationPoint,
} from "../src/lib/simulation/rolling";
import { simulateBacktest, simulateWithWarmUp } from "../src/lib/simulation/engine";
import {
  DEFAULT_FUTURES_ROLL_CALENDAR_DAYS_BEFORE_EXPIRY,
  simulateFuturesSmaStrategy,
  type FuturesStrategyResult,
} from "../src/lib/simulation/futures";
import { buildRunSummary } from "../src/lib/run-summary";
import { validateSimulationReadyPrices } from "../src/lib/utils";
import {
  precomputeAllConfigDailyValues,
  buildSimulationBuckets,
  runParallelBacktest,
  runParallelVariants,
} from "../src/lib/simulation/parallel";
import {
  annualizedInflationForRange,
  buildYearlyCpiInflation,
  sampleYearlyRealGrowth,
} from "../src/lib/inflation";
import {
  alignCloseSeriesToDates,
  alignOpenSeriesToDates,
  filterPricesByDates,
  intersectCommonDates,
} from "../src/lib/utils";
import { buildStrategyVariants, buildStrategyYearlyGrowthSeries, normalizeStrategyLabel, shouldIncludeStrategyChartLabel } from "../src/lib/strategy-page-data";
import { buildSgovFinalValuesByWindow } from "../src/lib/sgov-benchmark";
import { computeWinRatesByWindowLength, type WinRatesByWindow } from "../src/lib/simulation/win-rates";
import {
  dedupePoints,
  pickTopCell,
  planCoarseGrid,
  planFineGrid,
  type AsymmetricSweepRow,
} from "../src/lib/simulation/buffer-grid-search";

const OUTPUT_DIR = join(process.cwd(), "src", "lib", "tool-snapshots");
const MAX_SNAPSHOT_SIZE_BYTES = 5 * 1024 * 1024;
const FUTURES_SNAPSHOT_TARGET_POINTS = 1000;
const DATA_LATEST_END = "9999-12-31";

const PAGE_KEYS = [
  "compare-letfs",
  "compare-sma",
  "compare-threshold",
  "compare-riskoff-assets",
  "statistical-analysis",
  "backtesting",
  "futures",
] as const;

type PageKey = (typeof PAGE_KEYS)[number];

type StrategyResult = {
  label: string;
  runs: RollingSimulationPoint[];
};

type DistributionCategoryWinRates = {
  vsSma: number;
  vsNonSma: number;
  vsUnleveraged: number;
  vsSgov: number;
};

type DistributionSnapshot = {
  chart: {
    x: number[];
    series: Array<{
      key: string;
      label: string;
      color: string;
      borderWidth: number;
      y: number[];
    }>;
  };
  rows: Array<{
    label: string;
    p10: number;
    p50: number;
    avg: number;
    p90: number;
    categoryWinRates: DistributionCategoryWinRates;
  }>;
};

type YearlyGrowthSeries = {
  years: string[];
  series: Array<{ label: string; values: Array<number | null> }>;
  inflation?: Array<number | null>;
};

const DISTRIBUTION_LABEL_ORDER = [
  "TQQQ SMA Next Open",
  "TQQQ",
  LABEL_INDEX_NASDAQ100_TR,
  "UPRO SMA Next Open",
  "UPRO",
  LABEL_INDEX_SP500_TR,
] as const;

type UnleveragedSummary = {
  avg: number;
  median: number;
  best: number;
  worst: number;
};

type VariantSummary = {
  label: string;
  summary: ParallelBacktestResult;
  unleveraged: UnleveragedSummary;
};

type ComboSingleResult = {
  subPresetName: string;
  index: IndexKey;
  simulations: RollingSimulationPoint[];
  variantSummaries: VariantSummary[];
  variantRuns: { label: string; runs: RollingSimulationPoint[] }[];
  yearlyGrowthSeries: YearlyGrowthSeries | null;
};

type SharedInputs = {
  preset: string;
  startDate: string;
  endDate: string;
  windowLength: number;
  smaSpPeriod: number;
  smaNqPeriod: number;
  smaSpUpperBuffer: number;
  smaSpLowerBuffer: number;
  smaNqUpperBuffer: number;
  smaNqLowerBuffer: number;
  riskOffAsset: RiskOffAsset;
  smaExecutionMode: NonNullable<EtfConfig["smaExecutionMode"]>;
};

type PageSnapshot = {
  generatedAt: string;
  snapshotEndDate: string;
  sharedInputs: SharedInputs;
  pageKey: PageKey;
  pageState: Record<string, unknown>;
};

async function main() {
  const requestedPages = parseRequestedPages(process.argv.slice(2));
  const snapshotEndDate = await getLatestSharedTradeDate([
    "sp500",
    "nasdaq100",
    "risk:SGOV",
    "risk:VGSH",
    "risk:GLDM",
    "risk:BRKA",
  ]);
  const sharedInputs: SharedInputs = {
    preset: DEFAULT_COMBO_PRESET,
    startDate: CONSTANT_SP500_SHORTCUT_DATE,
    endDate: snapshotEndDate,
    windowLength: getDefaultWindowLength(),
    smaSpPeriod: getDefaultSmaPeriod("sp500"),
    smaNqPeriod: getDefaultSmaPeriod("nasdaq100"),
    smaSpUpperBuffer: getDefaultSmaBuffer("sp500"),
    smaSpLowerBuffer: getDefaultSmaBuffer("sp500"),
    smaNqUpperBuffer: getDefaultSmaBuffer("nasdaq100"),
    smaNqLowerBuffer: getDefaultSmaBuffer("nasdaq100"),
    riskOffAsset: DEFAULT_RISK_OFF_ASSET,
    smaExecutionMode: "next-day-open",
  } as const;

  console.log(`[snapshots] Using last shared trade date ${snapshotEndDate}`);

  mkdirSync(OUTPUT_DIR, { recursive: true });

  for (const pageKey of requestedPages) {
    console.log(`[snapshots] Building ${pageKey}...`);
    const pageState = await SNAPSHOT_BUILDERS[pageKey](sharedInputs);
    const payload: PageSnapshot = {
      generatedAt: new Date().toISOString(),
      snapshotEndDate,
      sharedInputs,
      pageKey,
      pageState,
    };
    const serialized = JSON.stringify(payload);
    const outputPath = getSnapshotPath(pageKey);
    const sizeBytes = Buffer.byteLength(serialized, "utf8");
    const maxBytes = MAX_SNAPSHOT_SIZE_BYTES;
    if (sizeBytes > maxBytes) {
      if (existsSync(outputPath)) {
        rmSync(outputPath);
      }
      const sizeKb = Math.round(sizeBytes / 1024);
      const limitKb = Math.round(maxBytes / 1024);
      console.log(`[snapshots] Skipped ${outputPath} (${sizeKb} KB > ${limitKb} KB limit)`);
      continue;
    }
    writeFileSync(outputPath, serialized);
    const sizeKb = Math.round(sizeBytes / 1024);
    console.log(`[snapshots] Wrote ${outputPath} (${sizeKb} KB)`);
  }
}

function parseRequestedPages(args: string[]): PageKey[] {
  const pageFlagIndex = args.findIndex((arg) => arg === "--page");
  const skipFlagIndex = args.findIndex((arg) => arg === "--skip");

  let pages: PageKey[];
  if (pageFlagIndex === -1) {
    pages = [...PAGE_KEYS];
  } else {
    const rawValue = args[pageFlagIndex + 1];
    if (!rawValue) {
      throw new Error("Missing value for --page. Use a page key or 'all'.");
    }
    if (rawValue === "all") {
      pages = [...PAGE_KEYS];
    } else {
      const requested = rawValue.split(",").map((page) => page.trim()).filter(Boolean);
      const invalid = requested.filter((page): page is string => !PAGE_KEYS.includes(page as PageKey));
      if (invalid.length > 0) {
        throw new Error(`Unknown page key(s): ${invalid.join(", ")}. Valid values: ${PAGE_KEYS.join(", ")}, all`);
      }
      pages = requested as PageKey[];
    }
  }

  if (skipFlagIndex !== -1) {
    const rawSkip = args[skipFlagIndex + 1];
    if (!rawSkip) {
      throw new Error("Missing value for --skip. Use comma-separated page keys.");
    }
    const skipped = new Set(rawSkip.split(",").map((p) => p.trim()).filter(Boolean));
    const invalidSkips = [...skipped].filter((p) => !PAGE_KEYS.includes(p as PageKey));
    if (invalidSkips.length > 0) {
      throw new Error(`Unknown skip key(s): ${invalidSkips.join(", ")}. Valid values: ${PAGE_KEYS.join(", ")}`);
    }
    pages = pages.filter((p) => !skipped.has(p));
  }

  return pages;
}

function getSnapshotPath(pageKey: PageKey): string {
  return join(OUTPUT_DIR, `${pageKey}.json`);
}

const SNAPSHOT_BUILDERS: Record<PageKey, (shared: SharedInputs) => Promise<Record<string, unknown>>> = {
  "compare-letfs": buildCompareLetfsSnapshot,
  "compare-sma": buildCompareSmaSnapshot,
  "compare-threshold": buildCompareThresholdSnapshot,
  "compare-riskoff-assets": buildCompareRiskOffAssetsSnapshot,
  "statistical-analysis": buildStatisticalAnalysisSnapshot,
  "backtesting": buildBacktestingSnapshot,
  "futures": buildFuturesSnapshot,
};

async function buildBacktestingSnapshot(shared: SharedInputs) {
  const comboSubs = getComboSubPresets(shared.preset);
  const resolvedEtfConfigs = comboSubs.map((preset, idx) =>
    createPresetEtfConfig(`etf${idx + 1}`, preset, {
      smaEnabled: true,
      smaPeriod: preset.index === "nasdaq100" ? shared.smaNqPeriod : shared.smaSpPeriod,
      smaUpperBuffer: preset.index === "nasdaq100" ? shared.smaNqUpperBuffer : shared.smaSpUpperBuffer, smaLowerBuffer: preset.index === "nasdaq100" ? shared.smaNqLowerBuffer : shared.smaSpLowerBuffer,
      riskOffAsset: shared.riskOffAsset,
    })
  );

  const primaryIndex: IndexKey = resolvedEtfConfigs[0]?.smaIndex ?? "sp500";
  const requiredIndexes = [...new Set(resolvedEtfConfigs.map((cfg) => cfg.smaIndex))] as IndexKey[];
  const displayStartDate = shared.startDate;
  const maxSmaPeriod = Math.max(0, ...resolvedEtfConfigs.map((cfg) => cfg.smaPeriod));
  const expandedStartDate = getSmaWarmupStartDate(displayStartDate, maxSmaPeriod);

  const priceRows = await Promise.all(requiredIndexes.map((idx) => loadPrices(idx, expandedStartDate, shared.endDate)));
  const pricesByIndex = Object.fromEntries(priceRows.map((prices, idx) => [requiredIndexes[idx], prices])) as Record<IndexKey, PricePoint[]>;
  const rates = await loadRates(expandedStartDate, shared.endDate);
  const inflationData = await fetchInflationData(displayStartDate, shared.endDate);
  const annualizedInflation =
    inflationData.monthlyCpi.length >= 2
      ? annualizedInflationForRange(inflationData.monthlyCpi, displayStartDate, shared.endDate)
      : inflationData.annualizedInflation;

  // Match UI behavior: anchor synthetic ETF price series to real ETF prices when available.
  // (See src/app/backtesting-tool/page.tsx which passes etfPricePointsByName into buildBacktestChartSeries.)
  const symbolsNeedingEtfPrices = [...new Set(
    resolvedEtfConfigs
      .filter((cfg) => cfg.simulated)
      .map((cfg) => cfg.name.replace(/-real$/, ""))
  )];
  const etfRows = await Promise.all(
    symbolsNeedingEtfPrices.map(async (symbol) => {
      const points = await loadPrices(`etf:${symbol}`, expandedStartDate, shared.endDate);
      return [symbol, points] as const;
    })
  );
  const etfPricePointsByName = Object.fromEntries(
    etfRows.filter(([, points]) => points.length > 0)
  ) as Record<string, PricePoint[]>;
  const primitiveRiskOffAssets = getUniquePrimitiveRiskOffAssets([shared.riskOffAsset]);
  const riskOffPricesByAsset = Object.fromEntries(
    await Promise.all(
      primitiveRiskOffAssets.map(async (asset) => {
        const storageKey =
          asset === "VOO"
            ? "sp500"
            : asset === "QQQ"
              ? "nasdaq100"
              : asset === "BRK.B"
                ? "risk:BRKA"
                : `risk:${asset.replace(".", "")}`;
        return [asset, await loadPrices(storageKey, expandedStartDate, shared.endDate)] as const;
      })
    )
  ) as Partial<Record<RiskOffAsset, PricePoint[]>>;

  // Use the same core path as the UI (workers + real-price anchoring) so dailyValues match.
  const canonicalRun = await runParallelBacktest({
    prices: pricesByIndex[primaryIndex],
    rates,
    startDate: displayStartDate,
    endDate: shared.endDate,
    configs: resolvedEtfConfigs,
    riskOffPricesByAsset,
    etfPricePointsByName,
    pricesByIndex,
  });
  if (!canonicalRun || canonicalRun.dates.length < 2) {
    throw new Error("No backtest results produced for snapshot.");
  }

  return {
    preset: shared.preset,
    index: primaryIndex,
    startDate: displayStartDate,
    endDate: shared.endDate,
    smaSpPeriod: shared.smaSpPeriod,
    smaNqPeriod: shared.smaNqPeriod,
    smaSpUpperBuffer: shared.smaSpUpperBuffer,
    smaSpLowerBuffer: shared.smaSpLowerBuffer,
    smaNqUpperBuffer: shared.smaNqUpperBuffer,
    smaNqLowerBuffer: shared.smaNqLowerBuffer,
    riskOffAsset: shared.riskOffAsset,
    smaMode: 1,
    etfConfigs: [],
    result: canonicalRun as BacktestResult,
    annualizedInflation,
  };
}

async function buildFuturesSnapshot(shared: SharedInputs) {
  const startDate = getFuturesDefaultStartDate(shared.endDate);
  const endDate = shared.endDate;
  const amount = DEFAULT_FUTURES_AMOUNT;
  const leverageTolerancePct = DEFAULT_LEVERAGE_TOLERANCE_PCT;

  const warmedStartDate = getSmaWarmupStartDate(
    startDate,
    Math.max(shared.smaSpPeriod, shared.smaNqPeriod),
  );

  const [spPrices, nqPrices, rates, inflationData] = await Promise.all([
    loadPrices("sp500", warmedStartDate, endDate),
    loadPrices("nasdaq100", warmedStartDate, endDate),
    loadRates(warmedStartDate, endDate),
    fetchInflationData(startDate, endDate),
  ]);
  if (spPrices.length < 2) throw new Error("SPX prices unavailable for futures snapshot.");
  const hasNqData = nqPrices.length >= 2;

  // Load raw risk-off price points + build aligned per-index arrays, mirroring
  // the futures page's runtime risk-off pipeline.
  const riskOffTickers = getRiskOffFetchTickers(shared.riskOffAsset);
  const rawRiskOffByTicker: Record<string, PricePoint[]> = {};
  for (const ticker of riskOffTickers) {
    const storageKey =
      ticker === "VOO"
        ? "sp500"
        : ticker === "QQQ"
          ? "nasdaq100"
          : ticker === "BRK.B"
            ? "risk:BRKA"
            : `risk:${ticker.replace(".", "")}`;
    rawRiskOffByTicker[ticker] = await loadPrices(storageKey, warmedStartDate, endDate);
  }

  const buildRiskOffAligned = (basePrices: PricePoint[]) => {
    const closeByTicker: Record<string, number[]> = {};
    const openByTicker: Record<string, number[]> = {};
    for (const ticker of riskOffTickers) {
      const series = rawRiskOffByTicker[ticker];
      if (!series || series.length === 0) {
        closeByTicker[ticker] = new Array(basePrices.length).fill(NaN);
        openByTicker[ticker] = new Array(basePrices.length).fill(NaN);
        continue;
      }
      closeByTicker[ticker] = alignCloseSeriesToDates(basePrices, series);
      openByTicker[ticker] = alignOpenSeriesToDates(basePrices, series);
    }
    return { closeByTicker, openByTicker };
  };

  const spInRange = spPrices.filter((p) => p.date >= startDate && p.date <= endDate);
  const nqInRange = nqPrices.filter((p) => p.date >= startDate && p.date <= endDate);
  const spRiskOffAligned = buildRiskOffAligned(spInRange);
  const nqRiskOffAligned = buildRiskOffAligned(nqInRange);

  const spPriceAnchor = spPrices[spPrices.length - 1]?.close ?? spPrices[spPrices.length - 1]?.adj_close;
  const nqPriceAnchor = nqPrices[nqPrices.length - 1]?.close ?? nqPrices[nqPrices.length - 1]?.adj_close;

  // Match the futures page's non-emulation plan selection (yearSpan-driven).
  const yearSpan =
    (new Date(`${endDate}T00:00:00Z`).getTime() - new Date(`${startDate}T00:00:00Z`).getTime()) /
    (1000 * 60 * 60 * 24 * 365.25);
  const futuresPlan: Array<{
    index: "sp500" | "nasdaq100";
    leverage: number;
    maxLeverage?: number;
    displayName?: string;
    period: number;
    buffer: number;
  }> =
    yearSpan > 90
      ? [
          { index: "sp500", leverage: 4.5, maxLeverage: 4.5, displayName: "Max 4.5x SPX SMA", period: shared.smaSpPeriod, buffer: shared.smaSpUpperBuffer },
          { index: "sp500", leverage: 3, period: shared.smaSpPeriod, buffer: shared.smaSpUpperBuffer },
        ]
      : [
          { index: "sp500", leverage: 4.5, maxLeverage: 4.5, displayName: "Max 4.5x SPX SMA", period: shared.smaSpPeriod, buffer: shared.smaSpUpperBuffer },
          { index: "sp500", leverage: 5, period: shared.smaSpPeriod, buffer: shared.smaSpUpperBuffer },
          { index: "sp500", leverage: 3, period: shared.smaSpPeriod, buffer: shared.smaSpUpperBuffer },
          ...(hasNqData
            ? ([
                { index: "nasdaq100" as const, leverage: 4, period: shared.smaNqPeriod, buffer: shared.smaNqUpperBuffer },
                { index: "nasdaq100" as const, leverage: 3, period: shared.smaNqPeriod, buffer: shared.smaNqUpperBuffer },
              ])
            : []),
        ];

  const futuresRuns: FuturesStrategyResult[] = futuresPlan
    .filter((step) => step.index !== "nasdaq100" || hasNqData)
    .map((step) =>
      simulateFuturesSmaStrategy({
        index: step.index,
        prices: step.index === "sp500" ? spPrices : nqPrices,
        rates,
        startDate,
        endDate,
        initialEquity: amount,
        targetLeverage: step.leverage,
        maxLeverage: step.maxLeverage,
        displayName: step.displayName,
        smaPeriod: step.period,
        smaUpperBuffer: step.buffer, smaLowerBuffer: step.buffer,
        riskOffAsset: shared.riskOffAsset,
        riskOffCloseByTicker: step.index === "sp500" ? spRiskOffAligned.closeByTicker : nqRiskOffAligned.closeByTicker,
        riskOffOpenByTicker: step.index === "sp500" ? spRiskOffAligned.openByTicker : nqRiskOffAligned.openByTicker,
        leverageTolerancePct,
        rollCalendarDaysBeforeExpiry: DEFAULT_FUTURES_ROLL_CALENDAR_DAYS_BEFORE_EXPIRY,
        monthlyCpi: inflationData.monthlyCpi,
        futuresPriceAnchor: step.index === "sp500" ? spPriceAnchor : nqPriceAnchor,
      }),
    );

  // Global date axis = union of SP + NQ trading days in range, sorted.
  const spDisplay = validateSimulationReadyPrices("sp500", spPrices, endDate).filter(
    (p) => p.date >= startDate && p.date <= endDate,
  );
  const nqDisplay = validateSimulationReadyPrices("nasdaq100", nqPrices, endDate).filter(
    (p) => p.date >= startDate && p.date <= endDate,
  );
  const dateSet = new Set<string>([...spDisplay.map((p) => p.date), ...nqDisplay.map((p) => p.date)]);
  const globalDates = Array.from(dateSet).sort((a, b) => a.localeCompare(b));

  // Unleveraged baseline: SP500 total return scaled to amount.
  const spAdjByDate = new Map(spDisplay.map((p) => [p.date, p.adj_close] as const));
  let lastAdj = spDisplay[0]?.adj_close ?? 1;
  const nonLeveragedValues = globalDates.map((d) => {
    const v = spAdjByDate.get(d);
    if (Number.isFinite(v ?? NaN) && (v as number) > 0) lastAdj = v as number;
    return lastAdj;
  });
  const baseAdj = nonLeveragedValues[0] ?? 1;
  const scaledNonLeveraged = nonLeveragedValues.map((v) => (baseAdj > 0 ? (v / baseAdj) * amount : amount));
  const investedValues = new Array(globalDates.length).fill(amount);

  const fullResult: BacktestResult = {
    dates: globalDates,
    nonLeveragedValues: scaledNonLeveraged,
    investedValues,
    etfResults: futuresRuns.map((r) => r.etfResult),
  };

  // The full payload (per-day arrays + all transactions for all strategies)
  // weighs ~5.7 MB. Two-step shrink to keep the cached snapshot small:
  // 1. Downsample per-day arrays to ~1000 points — visually indistinguishable
  //    from the full series at normal chart widths.
  // 2. Drop transactions[] for strategies that the Transactions section never
  //    renders (the UI filter at futures-tool/page.tsx shows only the 4.5×
  //    SPX and 3× NDX entries in the default non-emulation view). The other
  //    entries still need to be present in futuresDetails because the page
  //    derives scalar metrics (avgActualLeverageById, maxLeverageDeltaById)
  //    from them.
  const combinedResult = downsampleBacktestResult(fullResult, FUTURES_SNAPSHOT_TARGET_POINTS);
  const isShownInTransactionsSection = (run: FuturesStrategyResult): boolean =>
    (run.index === "sp500" && run.targetLeverage === 4.5) ||
    (run.index === "nasdaq100" && run.targetLeverage === 3);
  const downsampledFuturesRuns: FuturesStrategyResult[] = futuresRuns.map((run) => ({
    ...run,
    etfResult: downsampleEtfResult(run.etfResult, FUTURES_SNAPSHOT_TARGET_POINTS),
    transactions: isShownInTransactionsSection(run) ? run.transactions : [],
  }));

  const runSummaryInputs = buildRunSummary({
    startDate,
    endDate: globalDates[globalDates.length - 1] ?? endDate,
    letf: "FUTURES",
    windowLength: shared.windowLength,
    smaSpPeriod: shared.smaSpPeriod,
    smaSpUpperBuffer: shared.smaSpUpperBuffer,
    smaSpLowerBuffer: shared.smaSpLowerBuffer,
    smaNqPeriod: shared.smaNqPeriod,
    smaNqUpperBuffer: shared.smaNqUpperBuffer,
    smaNqLowerBuffer: shared.smaNqLowerBuffer,
    riskOffAsset: shared.riskOffAsset,
    amount,
    leverageTolerance: `${leverageTolerancePct}%`,
  });

  const annualizedInflation =
    inflationData.monthlyCpi.length >= 2
      ? annualizedInflationForRange(inflationData.monthlyCpi, startDate, endDate)
      : inflationData.annualizedInflation;

  return {
    startDate,
    endDate,
    windowLength: shared.windowLength,
    smaSpPeriod: shared.smaSpPeriod,
    smaNqPeriod: shared.smaNqPeriod,
    smaSpUpperBuffer: shared.smaSpUpperBuffer,
    smaNqUpperBuffer: shared.smaNqUpperBuffer,
    riskOffAsset: shared.riskOffAsset,
    amount,
    leverageTolerancePct,
    result: combinedResult,
    futuresDetails: downsampledFuturesRuns,
    annualizedInflation,
    monthlyCpi: inflationData.monthlyCpi,
    runSummaryInputs,
  };
}

async function buildStatisticalAnalysisSnapshot(shared: SharedInputs) {
  const comboSubs = getComboSubPresets(shared.preset);
  const expandedStartDate = getSmaWarmupStartDate(
    shared.startDate,
    Math.max(shared.smaSpPeriod, shared.smaNqPeriod)
  );
  const [inflationData, rates, sp500Prices, nasdaqPrices, sgovPoints] = await Promise.all([
    fetchInflationData(shared.startDate, shared.endDate),
    loadRates(expandedStartDate, shared.endDate),
    loadPrices("sp500", expandedStartDate, shared.endDate),
    loadPrices("nasdaq100", expandedStartDate, shared.endDate),
    loadPrices("risk:SGOV", expandedStartDate, DATA_LATEST_END),
  ]);
  const [riskOffSp500, riskOffNasdaq] = await Promise.all([
    loadRiskOffValuesForReference(
      getUniquePrimitiveRiskOffAssets([shared.riskOffAsset]),
      sp500Prices,
      expandedStartDate,
      shared.endDate
    ),
    loadRiskOffValuesForReference(
      getUniquePrimitiveRiskOffAssets([shared.riskOffAsset]),
      nasdaqPrices,
      expandedStartDate,
      shared.endDate
    ),
  ]);
  const winRatesByWindow: WinRatesByWindow[] = [];

  for (const sub of comboSubs) {
    const prices = sub.index === "nasdaq100" ? nasdaqPrices : sp500Prices;
    const riskOffSeriesForSub = sub.index === "nasdaq100" ? riskOffNasdaq : riskOffSp500;
    const smaConfig: EtfConfig = createPresetEtfConfig(`${sub.name}-wr-sma`, sub, {
      smaEnabled: true,
      smaPeriod: sub.index === "nasdaq100" ? shared.smaNqPeriod : shared.smaSpPeriod,
      smaUpperBuffer: sub.index === "nasdaq100" ? shared.smaNqUpperBuffer : shared.smaSpUpperBuffer, smaLowerBuffer: sub.index === "nasdaq100" ? shared.smaNqLowerBuffer : shared.smaSpLowerBuffer,
      riskOffAsset: shared.riskOffAsset,
      smaExecutionMode: shared.smaExecutionMode,
    });
    const noSmaConfig: EtfConfig = { ...smaConfig, id: `${sub.name}-wr-nosma`, smaEnabled: false };
    const winRates = await computeWinRatesByWindowLength({
      label: sub.name,
      prices,
      rates,
      smaConfig,
      noSmaConfig,
      startDate: shared.startDate,
      endDate: shared.endDate,
      riskOffValuesByAsset: riskOffSeriesForSub.closeValuesByAsset,
      sgovPoints,
      monthlyCpi: inflationData.monthlyCpi,
    });
    winRatesByWindow.push(winRates);
  }

  return {
    preset: shared.preset,
    index: comboSubs[0].index,
    startDate: shared.startDate,
    endDate: shared.endDate,
    windowLength: shared.windowLength,
    smaSpPeriod: shared.smaSpPeriod,
    smaNqPeriod: shared.smaNqPeriod,
    smaSpUpperBuffer: shared.smaSpUpperBuffer,
    smaNqUpperBuffer: shared.smaNqUpperBuffer,
    riskOffAsset: shared.riskOffAsset,
    smaExecutionMode: shared.smaExecutionMode,
    annualizedInflation: inflationData.annualizedInflation,
    monthlyCpi: inflationData.monthlyCpi,
    runSummaryInputs: {
      startDate: shared.startDate,
      endDate: shared.endDate,
      smaSpPeriod: shared.smaSpPeriod,
      smaSpUpperBuffer: shared.smaSpUpperBuffer,
      smaNqPeriod: shared.smaNqPeriod,
      smaNqUpperBuffer: shared.smaNqUpperBuffer,
      letf: shared.preset,
      riskOffAsset: shared.riskOffAsset,
    },
    winRatesByWindow,
  };
}

async function buildCompareLetfsSnapshot(shared: SharedInputs) {
  const expandedStartDate = getSmaWarmupStartDate(
    shared.startDate,
    Math.max(shared.smaSpPeriod, shared.smaNqPeriod)
  );
  const [sp500Prices, nasdaqPrices, rates, inflationData, sgovPoints] = await Promise.all([
    loadPrices("sp500", expandedStartDate, DATA_LATEST_END),
    loadPrices("nasdaq100", expandedStartDate, DATA_LATEST_END),
    loadRates(expandedStartDate, DATA_LATEST_END),
    fetchInflationData(shared.startDate, shared.endDate),
    loadPrices("risk:SGOV", expandedStartDate, DATA_LATEST_END),
  ]);

  const [riskOffForSp500, riskOffForNasdaq] = await Promise.all([
    loadRiskOffValuesForReference(
      getUniquePrimitiveRiskOffAssets([shared.riskOffAsset]),
      sp500Prices,
      expandedStartDate,
      DATA_LATEST_END
    ),
    loadRiskOffValuesForReference(
      getUniquePrimitiveRiskOffAssets([shared.riskOffAsset]),
      nasdaqPrices,
      expandedStartDate,
      DATA_LATEST_END
    ),
  ]);

  const { sp500Variants, nasdaqVariants } = buildStrategyVariants({
    smaSpPeriod: shared.smaSpPeriod,
    smaNqPeriod: shared.smaNqPeriod,
    smaSpUpperBuffer: shared.smaSpUpperBuffer,
    smaSpLowerBuffer: shared.smaSpLowerBuffer,
    smaNqUpperBuffer: shared.smaNqUpperBuffer,
    smaNqLowerBuffer: shared.smaNqLowerBuffer,
    riskOffAsset: shared.riskOffAsset,
  });

  const [sp500Results, nasdaqResults] = await Promise.all([
    runParallelVariants({
      prices: sp500Prices,
      rates,
      windowLength: shared.windowLength,
      startDate: shared.startDate,
      endDate: shared.endDate,
      variants: sp500Variants,
      riskOffValuesByAsset: riskOffForSp500.closeValuesByAsset,
      riskOffOpenValuesByAsset: riskOffForSp500.openValuesByAsset,
    }),
    runParallelVariants({
      prices: nasdaqPrices,
      rates,
      windowLength: shared.windowLength,
      startDate: shared.startDate,
      endDate: shared.endDate,
      variants: nasdaqVariants,
      riskOffValuesByAsset: riskOffForNasdaq.closeValuesByAsset,
      riskOffOpenValuesByAsset: riskOffForNasdaq.openValuesByAsset,
    }),
  ]);

  const strategyResults: StrategyResult[] = [
    ...sp500Results.map(({ label, simulations }) => ({ label, runs: simulations })),
    ...nasdaqResults.map(({ label, simulations }) => ({ label, runs: simulations })),
  ];
  const snapshotSummary = {
    rows: strategyResults.map((result, idx) => summarizeSmaRow(idx, result.runs, inflationData.monthlyCpi)),
    labels: strategyResults.map((result) => result.label),
  };
  const distributionSnapshot = buildCompareLetfsDistributionSnapshot(
    strategyResults,
    inflationData.monthlyCpi,
    CONSTANT_INITIAL_INVESTMENT,
    sgovPoints
  );

  const sp500Backtest = simulateWithWarmUp(
    sp500Prices,
    rates,
    sp500Variants.map((variant) => variant.config),
    shared.startDate,
    1000,
    {
      riskOffValuesByAsset: riskOffForSp500.closeValuesByAsset,
      riskOffOpenValuesByAsset: riskOffForSp500.openValuesByAsset,
      endDate: shared.endDate,
    }
  );
  const nasdaqBacktest = simulateWithWarmUp(
    nasdaqPrices,
    rates,
    nasdaqVariants.map((variant) => variant.config),
    shared.startDate,
    1000,
    {
      riskOffValuesByAsset: riskOffForNasdaq.closeValuesByAsset,
      riskOffOpenValuesByAsset: riskOffForNasdaq.openValuesByAsset,
      endDate: shared.endDate,
    }
  );
  const yearlyGrowthSeries = buildStrategyYearlyGrowthSeries({
    sp500Backtest,
    nasdaqBacktest,
    sp500Variants,
    nasdaqVariants,
    monthlyCpi: inflationData.monthlyCpi,
  });

  return {
    startDate: shared.startDate,
    endDate: shared.endDate,
    windowLength: shared.windowLength,
    smaSpPeriod: shared.smaSpPeriod,
    smaNqPeriod: shared.smaNqPeriod,
    smaSpUpperBuffer: shared.smaSpUpperBuffer,
    smaNqUpperBuffer: shared.smaNqUpperBuffer,
    riskOffAsset: shared.riskOffAsset,
    smaExecutionMode: shared.smaExecutionMode,
    annualizedInflation: inflationData.annualizedInflation,
    monthlyCpi: inflationData.monthlyCpi,
    strategyResults: [],
    snapshotSummary,
    distributionSnapshot,
    yearlyGrowthSeries,
  };
}

async function buildCompareSmaSnapshot(shared: SharedInputs) {
  return buildSmaSweepSnapshot(shared, { minSmaPeriod: 20, maxSmaPeriod: 280, stepSize: 5 });
}

async function buildCompareThresholdSnapshot(shared: SharedInputs) {
  // Match compare-threshold-strategies page defaults (symmetric + asymmetric grid).
  return buildBufferSweepSnapshot(shared, {
    minBuffer: 0,
    maxBuffer: 12,
    fineStep: 0.5,
    coarseStep: 2,
    fineHalfWidth: 1.5,
  });
}

async function buildCompareRiskOffAssetsSnapshot(shared: SharedInputs) {
  const comboSubs = getComboSubPresets(shared.preset);
  const expandedStartDate = getSmaWarmupStartDate(
    shared.startDate,
    Math.max(shared.smaSpPeriod, shared.smaNqPeriod)
  );
  const inflationData = await fetchInflationData(shared.startDate, shared.endDate);
  const [rates, sp500Prices, nasdaqPrices] = await Promise.all([
    loadRates(expandedStartDate, shared.endDate),
    loadPrices("sp500", expandedStartDate, shared.endDate),
    loadPrices("nasdaq100", expandedStartDate, shared.endDate),
  ]);
  const allPrimitiveAssets = getUniquePrimitiveRiskOffAssets(
    RISK_OFF_ASSET_OPTIONS.map((opt) => opt.value as RiskOffAsset)
  );
  const [riskOffSp500, riskOffNasdaq] = await Promise.all([
    loadRiskOffValuesForReference(allPrimitiveAssets, sp500Prices, expandedStartDate, shared.endDate),
    loadRiskOffValuesForReference(allPrimitiveAssets, nasdaqPrices, expandedStartDate, shared.endDate),
  ]);

  const results = await Promise.all(
    comboSubs.map(async (preset) => {
      const prices = preset.index === "nasdaq100" ? nasdaqPrices : sp500Prices;
      const riskOffSeries = preset.index === "nasdaq100" ? riskOffNasdaq : riskOffSp500;
      // Build all risk-off configs + baseline, precompute once, then slice
      const allConfigs: EtfConfig[] = RISK_OFF_ASSET_OPTIONS.map((opt) => {
        const asset = opt.value as RiskOffAsset;
        return createPresetEtfConfig(`riskoff-${asset}`, preset, {
          name: `${preset.leverage}x SMA ${preset.index === "nasdaq100" ? shared.smaNqPeriod : shared.smaSpPeriod} (${asset})`,
          smaEnabled: true,
          smaPeriod: preset.index === "nasdaq100" ? shared.smaNqPeriod : shared.smaSpPeriod,
          smaUpperBuffer: preset.index === "nasdaq100" ? shared.smaNqUpperBuffer : shared.smaSpUpperBuffer, smaLowerBuffer: preset.index === "nasdaq100" ? shared.smaNqLowerBuffer : shared.smaSpLowerBuffer,
          riskOffAsset: asset,
          smaExecutionMode: shared.smaExecutionMode,
        });
      });
      const baselineConfig = createPresetEtfConfig("baseline", preset, {
        name: `${preset.leverage}x Baseline`,
        simulated: true,
        smaEnabled: false,
        smaPeriod: preset.index === "nasdaq100" ? shared.smaNqPeriod : shared.smaSpPeriod,
        smaUpperBuffer: 0, smaLowerBuffer: 0,
        riskOffAsset: shared.riskOffAsset,
        smaExecutionMode: shared.smaExecutionMode,
      });
      allConfigs.push(baselineConfig);
      const windows = buildRollingWindows({
        prices,
        windowLength: shared.windowLength,
        startDateConstraint: shared.startDate,
        endDateConstraint: shared.endDate,
      });
      const sweepResults = runPrecomputedSweep({
        prices,
        rates,
        configs: allConfigs,
        windows,
        riskOffValuesByAsset: riskOffSeries.closeValuesByAsset,
        riskOffOpenValuesByAsset: riskOffSeries.openValuesByAsset,
      });
      const rows = RISK_OFF_ASSET_OPTIONS.map((opt) => {
        const asset = opt.value as RiskOffAsset;
        const simulations = sweepResults.get(`riskoff-${asset}`) ?? [];
        return {
          riskOffAsset: asset,
          displayLabel: opt.label,
          summary: summarizeSmaRow(0, simulations, inflationData.monthlyCpi),
        };
      });
      const baselineSims = sweepResults.get("baseline") ?? [];
      return {
        rows,
        baseline: baselineSims.length > 0 ? summarizeSmaRow(0, baselineSims, inflationData.monthlyCpi) : null,
      };
    })
  );

  return {
    preset: shared.preset,
    index: "sp500" as IndexKey,
    startDate: shared.startDate,
    endDate: shared.endDate,
    windowLength: shared.windowLength,
    smaSpPeriod: shared.smaSpPeriod,
    smaNqPeriod: shared.smaNqPeriod,
    smaSpUpperBuffer: shared.smaSpUpperBuffer,
    smaNqUpperBuffer: shared.smaNqUpperBuffer,
    smaExecutionMode: shared.smaExecutionMode,
    showBaseline: true,
    annualizedInflation: inflationData.annualizedInflation,
    monthlyCpi: inflationData.monthlyCpi,
    rows: results[0]?.rows ?? [],
    baseline: results[0]?.baseline ?? null,
    rows2: results[1]?.rows ?? [],
    baseline2: results[1]?.baseline ?? null,
  };
}

async function buildSmaSweepSnapshot(
  shared: SharedInputs,
  params: { minSmaPeriod: number; maxSmaPeriod: number; stepSize: number }
) {
  const comboSubs = getComboSubPresets(shared.preset);
  const expandedStartDate = getSmaWarmupStartDate(shared.startDate, params.maxSmaPeriod);
  const inflationData = await fetchInflationData(shared.startDate, shared.endDate);
  const [rates, sp500Prices, nasdaqPrices] = await Promise.all([
    loadRates(expandedStartDate, shared.endDate),
    loadPrices("sp500", expandedStartDate, shared.endDate),
    loadPrices("nasdaq100", expandedStartDate, shared.endDate),
  ]);
  const [riskOffSp500, riskOffNasdaq] = await Promise.all([
    loadRiskOffValuesForReference(
      getUniquePrimitiveRiskOffAssets([shared.riskOffAsset]),
      sp500Prices,
      expandedStartDate,
      shared.endDate
    ),
    loadRiskOffValuesForReference(
      getUniquePrimitiveRiskOffAssets([shared.riskOffAsset]),
      nasdaqPrices,
      expandedStartDate,
      shared.endDate
    ),
  ]);

  const results = comboSubs.map((preset) => {
    const prices = preset.index === "nasdaq100" ? nasdaqPrices : sp500Prices;
    const riskOffSeries = preset.index === "nasdaq100" ? riskOffNasdaq : riskOffSp500;
    const windows = buildRollingWindows({
      prices,
      windowLength: shared.windowLength,
      startDateConstraint: shared.startDate,
      endDateConstraint: shared.endDate,
    });
    // Build all SMA configs + baseline, precompute once, then slice
    const allConfigs: EtfConfig[] = [];
    for (let sma = params.minSmaPeriod; sma <= params.maxSmaPeriod; sma += params.stepSize) {
      allConfigs.push(createPresetEtfConfig(`sma-${sma}`, preset, {
        name: `${preset.leverage}x SMA ${sma}`,
        smaEnabled: true,
        smaPeriod: sma,
        smaUpperBuffer: preset.index === "nasdaq100" ? shared.smaNqUpperBuffer : shared.smaSpUpperBuffer, smaLowerBuffer: preset.index === "nasdaq100" ? shared.smaNqLowerBuffer : shared.smaSpLowerBuffer,
        riskOffAsset: shared.riskOffAsset,
        smaExecutionMode: shared.smaExecutionMode,
      }));
    }
    const baselineConfig = createPresetEtfConfig("baseline", preset, {
      name: `${preset.leverage}x Baseline`,
      simulated: true,
      smaEnabled: false,
      smaPeriod: getDefaultSmaPeriod(preset.index),
      smaUpperBuffer: 0, smaLowerBuffer: 0,
      riskOffAsset: shared.riskOffAsset,
      smaExecutionMode: shared.smaExecutionMode,
    });
    allConfigs.push(baselineConfig);
    const sweepResults = runPrecomputedSweep({
      prices,
      rates,
      configs: allConfigs,
      windows,
      riskOffValuesByAsset: riskOffSeries.closeValuesByAsset,
      riskOffOpenValuesByAsset: riskOffSeries.openValuesByAsset,
    });
    const rows: SmaComparisonRow[] = [];
    for (let sma = params.minSmaPeriod; sma <= params.maxSmaPeriod; sma += params.stepSize) {
      const simulations = sweepResults.get(`sma-${sma}`) ?? [];
      rows.push(summarizeSmaRow(sma, simulations, inflationData.monthlyCpi));
    }
    const baselineSims = sweepResults.get("baseline") ?? [];
    return {
      rows,
      baseline: baselineSims.length > 0 ? summarizeSmaRow(0, baselineSims, inflationData.monthlyCpi) : null,
    };
  });

  return {
    preset: shared.preset,
    index: "sp500" as IndexKey,
    startDate: shared.startDate,
    endDate: shared.endDate,
    windowLength: shared.windowLength,
    minSmaPeriod: params.minSmaPeriod,
    maxSmaPeriod: params.maxSmaPeriod,
    stepSize: params.stepSize,
    smaSpUpperBuffer: shared.smaSpUpperBuffer,
    smaNqUpperBuffer: shared.smaNqUpperBuffer,
    riskOffAsset: shared.riskOffAsset,
    smaExecutionMode: shared.smaExecutionMode,
    showBaseline: true,
    annualizedInflation: inflationData.annualizedInflation,
    monthlyCpi: inflationData.monthlyCpi,
    rows: results[0]?.rows ?? [],
    baseline: results[0]?.baseline ?? null,
    rows2: results[1]?.rows ?? [],
    baseline2: results[1]?.baseline ?? null,
  };
}

async function buildBufferSweepSnapshot(
  shared: SharedInputs,
  params: {
    minBuffer: number;
    maxBuffer: number;
    fineStep: number;
    coarseStep: number;
    fineHalfWidth: number;
  }
) {
  const comboSubs = getComboSubPresets(shared.preset);
  const expandedStartDate = getSmaWarmupStartDate(
    shared.startDate,
    Math.max(shared.smaSpPeriod, shared.smaNqPeriod)
  );
  const inflationData = await fetchInflationData(shared.startDate, shared.endDate);
  const inflPct = inflationData.monthlyCpi.length >= 2 ? 0 : inflationData.annualizedInflation * 100;
  const [rates, sp500Prices, nasdaqPrices] = await Promise.all([
    loadRates(expandedStartDate, shared.endDate),
    loadPrices("sp500", expandedStartDate, shared.endDate),
    loadPrices("nasdaq100", expandedStartDate, shared.endDate),
  ]);
  const [riskOffSp500, riskOffNasdaq] = await Promise.all([
    loadRiskOffValuesForReference(
      getUniquePrimitiveRiskOffAssets([shared.riskOffAsset]),
      sp500Prices,
      expandedStartDate,
      shared.endDate
    ),
    loadRiskOffValuesForReference(
      getUniquePrimitiveRiskOffAssets([shared.riskOffAsset]),
      nasdaqPrices,
      expandedStartDate,
      shared.endDate
    ),
  ]);

  const coarsePoints = planCoarseGrid({
    minUpper: params.minBuffer,
    maxUpper: params.maxBuffer,
    minLower: params.minBuffer,
    maxLower: params.maxBuffer,
    coarseStep: params.coarseStep,
  });

  const results = comboSubs.map((preset) => {
    const prices = preset.index === "nasdaq100" ? nasdaqPrices : sp500Prices;
    const riskOffSeries = preset.index === "nasdaq100" ? riskOffNasdaq : riskOffSp500;
    const period = preset.index === "nasdaq100" ? shared.smaNqPeriod : shared.smaSpPeriod;
    const windows = buildRollingWindows({
      prices,
      windowLength: shared.windowLength,
      startDateConstraint: shared.startDate,
      endDateConstraint: shared.endDate,
    });

    // Symmetric 1D sweep + baseline + coarse asymmetric grid in one precompute.
    const allConfigs: EtfConfig[] = [];
    for (let buffer = params.minBuffer; buffer <= params.maxBuffer + 1e-9; buffer += params.fineStep) {
      const roundedBuffer = Number(buffer.toFixed(6));
      allConfigs.push(createPresetEtfConfig(`buffer-${roundedBuffer}`, preset, {
        name: `${preset.leverage}x SMA ${roundedBuffer}%`,
        smaEnabled: true,
        smaPeriod: period,
        smaUpperBuffer: roundedBuffer, smaLowerBuffer: roundedBuffer,
        riskOffAsset: shared.riskOffAsset,
        smaExecutionMode: shared.smaExecutionMode,
      }));
    }
    allConfigs.push(createPresetEtfConfig("baseline", preset, {
      name: `${preset.leverage}x Baseline`,
      simulated: true,
      smaEnabled: false,
      smaPeriod: period,
      smaUpperBuffer: 0, smaLowerBuffer: 0,
      riskOffAsset: shared.riskOffAsset,
      smaExecutionMode: shared.smaExecutionMode,
    }));
    for (const { upper, lower } of coarsePoints) {
      allConfigs.push(createPresetEtfConfig(`asym-${upper}-${lower}`, preset, {
        name: `${preset.leverage}x SMA U${upper}/L${lower}`,
        smaEnabled: true,
        smaPeriod: period,
        smaUpperBuffer: upper, smaLowerBuffer: lower,
        riskOffAsset: shared.riskOffAsset,
        smaExecutionMode: shared.smaExecutionMode,
      }));
    }

    const sweepResults = runPrecomputedSweep({
      prices,
      rates,
      configs: allConfigs,
      windows,
      riskOffValuesByAsset: riskOffSeries.closeValuesByAsset,
      riskOffOpenValuesByAsset: riskOffSeries.openValuesByAsset,
    });

    const rows: SmaComparisonRow[] = [];
    for (let buffer = params.minBuffer; buffer <= params.maxBuffer + 1e-9; buffer += params.fineStep) {
      const roundedBuffer = Number(buffer.toFixed(6));
      const simulations = sweepResults.get(`buffer-${roundedBuffer}`) ?? [];
      rows.push(summarizeSmaRow(roundedBuffer, simulations, inflationData.monthlyCpi));
    }
    const baselineSims = sweepResults.get("baseline") ?? [];

    const coarseRows: AsymmetricSweepRow[] = coarsePoints.map(({ upper, lower }) => {
      const simulations = sweepResults.get(`asym-${upper}-${lower}`) ?? [];
      return {
        ...summarizeSmaRow(upper, simulations, inflationData.monthlyCpi),
        upperBuffer: upper,
        lowerBuffer: lower,
        stage: "coarse",
      };
    });

    const topCoarse = pickTopCell(coarseRows, "score", inflPct);
    let asymRows: AsymmetricSweepRow[] = coarseRows;
    let fineWindow: { minU: number; maxU: number; minL: number; maxL: number } | null = null;

    if (topCoarse) {
      fineWindow = {
        minU: Math.max(params.minBuffer, topCoarse.upperBuffer - params.fineHalfWidth),
        maxU: Math.min(params.maxBuffer, topCoarse.upperBuffer + params.fineHalfWidth),
        minL: Math.max(params.minBuffer, topCoarse.lowerBuffer - params.fineHalfWidth),
        maxL: Math.min(params.maxBuffer, topCoarse.lowerBuffer + params.fineHalfWidth),
      };
      const finePoints = dedupePoints(
        planFineGrid({
          centerUpper: topCoarse.upperBuffer,
          centerLower: topCoarse.lowerBuffer,
          halfWidth: params.fineHalfWidth,
          fineStep: params.fineStep,
          bounds: {
            minUpper: params.minBuffer,
            maxUpper: params.maxBuffer,
            minLower: params.minBuffer,
            maxLower: params.maxBuffer,
          },
        }),
        coarsePoints
      );
      if (finePoints.length > 0) {
        const fineConfigs = finePoints.map(({ upper, lower }) =>
          createPresetEtfConfig(`asym-${upper}-${lower}`, preset, {
            name: `${preset.leverage}x SMA U${upper}/L${lower} (fine)`,
            smaEnabled: true,
            smaPeriod: period,
            smaUpperBuffer: upper, smaLowerBuffer: lower,
            riskOffAsset: shared.riskOffAsset,
            smaExecutionMode: shared.smaExecutionMode,
          })
        );
        const fineResults = runPrecomputedSweep({
          prices,
          rates,
          configs: fineConfigs,
          windows,
          riskOffValuesByAsset: riskOffSeries.closeValuesByAsset,
          riskOffOpenValuesByAsset: riskOffSeries.openValuesByAsset,
        });
        const fineRows: AsymmetricSweepRow[] = finePoints.map(({ upper, lower }) => {
          const simulations = fineResults.get(`asym-${upper}-${lower}`) ?? [];
          return {
            ...summarizeSmaRow(upper, simulations, inflationData.monthlyCpi),
            upperBuffer: upper,
            lowerBuffer: lower,
            stage: "fine",
          };
        });
        asymRows = [...coarseRows, ...fineRows];
      }
    }

    return {
      rows,
      baseline: baselineSims.length > 0 ? summarizeSmaRow(0, baselineSims, inflationData.monthlyCpi) : null,
      asymRows,
      fineWindow,
    };
  });

  return {
    preset: shared.preset,
    index: "sp500" as IndexKey,
    startDate: shared.startDate,
    endDate: shared.endDate,
    windowLength: shared.windowLength,
    smaSpPeriod: shared.smaSpPeriod,
    smaNqPeriod: shared.smaNqPeriod,
    minBuffer: params.minBuffer,
    maxBuffer: params.maxBuffer,
    fineStep: params.fineStep,
    coarseStep: params.coarseStep,
    fineHalfWidth: params.fineHalfWidth,
    riskOffAsset: shared.riskOffAsset,
    smaExecutionMode: shared.smaExecutionMode,
    showBaseline: true,
    annualizedInflation: inflationData.annualizedInflation,
    monthlyCpi: inflationData.monthlyCpi,
    rows: results[0]?.rows ?? [],
    baseline: results[0]?.baseline ?? null,
    rows2: results[1]?.rows ?? [],
    baseline2: results[1]?.baseline ?? null,
    asymRows: results[0]?.asymRows ?? [],
    asymRows2: results[1]?.asymRows ?? [],
    asymFineWindow: results[0]?.fineWindow ?? null,
    asymFineWindow2: results[1]?.fineWindow ?? null,
  };
}

/**
 * Simulate a single config over the full date range, then slice rolling windows.
 * This matches the UI path (precompute-then-slice) instead of re-simulating each window.
 */
function runPrecomputedRolling({
  prices,
  rates,
  etfConfig,
  windowLength,
  startDateConstraint,
  endDateConstraint,
  riskOffValuesByAsset,
  riskOffOpenValuesByAsset,
}: {
  prices: PricePoint[];
  rates: RatePoint[];
  etfConfig: EtfConfig;
  windowLength: number;
  startDateConstraint: string;
  endDateConstraint: string;
  riskOffValuesByAsset?: Partial<Record<RiskOffAsset, number[]>>;
  riskOffOpenValuesByAsset?: Partial<Record<RiskOffAsset, number[]>>;
}): RollingSimulationPoint[] {
  const precomputed = precomputeAllConfigDailyValues(
    prices,
    rates,
    [etfConfig],
    riskOffValuesByAsset,
    riskOffOpenValuesByAsset
  );
  const windows = buildRollingWindows({
    prices,
    windowLength,
    startDateConstraint,
    endDateConstraint,
  });
  const buckets = buildSimulationBuckets(precomputed, windows, prices, {
    rates,
    configs: [etfConfig],
    riskOffValuesByAsset,
    riskOffOpenValuesByAsset,
  });
  return buckets[0]?.simulations ?? [];
}

function buildVariantSummary(label: string, runs: RollingSimulationPoint[]): VariantSummary {
  const summary = summarizeParallelResult(runs);
  return {
    label,
    summary,
    unleveraged: buildUnleveragedSummary(summary.nonLeveragedValues),
  };
}

function getDistributionComparisonLabels(label: string): {
  vsSma?: string;
  vsNonSma?: string;
  vsUnleveraged?: string;
} {
  switch (label) {
    case "TQQQ SMA Next Open":
      return { vsNonSma: "TQQQ", vsUnleveraged: LABEL_INDEX_NASDAQ100_TR };
    case "TQQQ":
      return { vsSma: "TQQQ SMA Next Open", vsUnleveraged: LABEL_INDEX_NASDAQ100_TR };
    case LABEL_INDEX_NASDAQ100_TR:
      return { vsSma: "TQQQ SMA Next Open", vsNonSma: "TQQQ" };
    case "UPRO SMA Next Open":
      return { vsNonSma: "UPRO", vsUnleveraged: LABEL_INDEX_SP500_TR };
    case "UPRO":
      return { vsSma: "UPRO SMA Next Open", vsUnleveraged: LABEL_INDEX_SP500_TR };
    case LABEL_INDEX_SP500_TR:
      return { vsSma: "UPRO SMA Next Open", vsNonSma: "UPRO" };
    default:
      return {};
  }
}

function compareValuesWithTie(left: number, right: number): number {
  if (left > right) return 1;
  if (left < right) return 0;
  return 0.5;
}

function getDistributionLabelOrder(label: string): number {
  const idx = DISTRIBUTION_LABEL_ORDER.indexOf(label as (typeof DISTRIBUTION_LABEL_ORDER)[number]);
  return idx === -1 ? Number.MAX_SAFE_INTEGER : idx;
}

function buildCompareLetfsDistributionSnapshot(
  strategyResults: StrategyResult[],
  monthlyCpi: MonthlyCpiPoint[],
  initialInvestment: number,
  sgovPoints: PricePoint[]
): DistributionSnapshot {
  const includedResults = strategyResults.filter((result) => shouldIncludeStrategyChartLabel(result.label));
  const chart = computeSharedHistogramDistribution(
    includedResults
      .map((result, idx) => ({
        key: result.label,
        label: normalizeStrategyLabel(result.label),
        color: CHART_COLORS.etf[idx % CHART_COLORS.etf.length],
        values: result.runs
          .map((run) => run.cagr - annualizedInflationForRange(monthlyCpi, run.startDate, run.endDate) * 100)
          .filter(Number.isFinite),
        borderWidth: 1.2,
      }))
      .filter((series) => series.values.some(Number.isFinite)),
    90
  );

  const byLabel = new Map(
    includedResults.map((result) => [
      normalizeStrategyLabel(result.label),
      new Map(result.runs.map((run) => [`${run.startDate}|${run.endDate}`, run] as const)),
    ])
  );
  const sgovFinalByWindow = buildSgovFinalValuesByWindow(
    includedResults.flatMap((result) => result.runs.map((run) => ({ startDate: run.startDate, endDate: run.endDate }))),
    sgovPoints,
    initialInvestment
  );

  const computeWinRate = (label: string, opponentLabel?: string): number => {
    if (!opponentLabel) return 0;
    const result = byLabel.get(label);
    const opponent = byLabel.get(opponentLabel);
    if (!result || !opponent) return 0;
    let total = 0;
    let wins = 0;
    for (const [key, run] of result.entries()) {
      const opponentRun = opponent.get(key);
      if (!opponentRun) continue;
      wins += compareValuesWithTie(run.finalValue, opponentRun.finalValue);
      total += 1;
    }
    return total === 0 ? 0 : (wins / total) * 100;
  };

  const computeWinRateVsSgov = (label: string): number => {
    const result = byLabel.get(label);
    if (!result) return 0;
    let total = 0;
    let wins = 0;
    for (const [key, run] of result.entries()) {
      const sgovFinal = sgovFinalByWindow.get(key);
      if (sgovFinal == null) continue;
      wins += compareValuesWithTie(run.finalValue, sgovFinal);
      total += 1;
    }
    return total === 0 ? 0 : (wins / total) * 100;
  };

  const rows = chart.series
    .map((series) => {
      const result = includedResults.find((item) => normalizeStrategyLabel(item.label) === series.label);
      if (!result) return null;
      const values = result.runs
        .map((run) => run.cagr - annualizedInflationForRange(monthlyCpi, run.startDate, run.endDate) * 100)
        .filter(Number.isFinite)
        .sort((a, b) => a - b);
      if (values.length === 0) return null;
      const comparisons = getDistributionComparisonLabels(series.label);
      return {
        label: series.label,
        p10: percentile(values, 0.1),
        p50: percentile(values, 0.5),
        avg: values.reduce((sum, value) => sum + value, 0) / values.length,
        p90: percentile(values, 0.9),
        categoryWinRates: {
          vsSma: computeWinRate(series.label, comparisons.vsSma),
          vsNonSma: computeWinRate(series.label, comparisons.vsNonSma),
          vsUnleveraged: computeWinRate(series.label, comparisons.vsUnleveraged),
          vsSgov: computeWinRateVsSgov(series.label),
        },
      };
    })
    .filter((row): row is DistributionSnapshot["rows"][number] => row !== null)
    .sort((a, b) => getDistributionLabelOrder(a.label) - getDistributionLabelOrder(b.label) || a.label.localeCompare(b.label));

  return { chart, rows };
}

function buildUnleveragedSummary(values: number[]): UnleveragedSummary {
  if (values.length === 0) {
    return { avg: 0, median: 0, best: 0, worst: 0 };
  }
  const sorted = [...values].sort((a, b) => a - b);
  return {
    avg: average(values),
    median: percentile(sorted, 0.5),
    best: Math.max(...values),
    worst: Math.min(...values),
  };
}

function computeSharedHistogramDistribution(
  inputSeries: Array<{
    key: string;
    label: string;
    color: string;
    values: number[];
    borderWidth: number;
  }>,
  requestedBins: number
): {
  x: number[];
  series: Array<{
    key: string;
    label: string;
    color: string;
    borderWidth: number;
    y: number[];
  }>;
} {
  const all = inputSeries.flatMap((series) => series.values).filter(Number.isFinite);
  if (all.length === 0) {
    return { x: [], series: [] };
  }

  const minValue = Math.min(...all);
  const maxValue = Math.max(...all);
  if (!Number.isFinite(minValue) || !Number.isFinite(maxValue)) {
    return { x: [], series: [] };
  }

  const bins = Math.max(20, Math.min(140, Math.round(requestedBins)));
  const span = Math.max(1e-9, maxValue - minValue);
  const binWidth = span / bins;
  const x = Array.from({ length: bins }, (_, i) => minValue + (i + 0.5) * binWidth);

  const toIndex = (value: number): number => {
    const normalized = Math.floor((value - minValue) / binWidth);
    return Math.max(0, Math.min(bins - 1, normalized));
  };

  const series = inputSeries.map((input) => {
    const counts = new Array<number>(bins).fill(0);
    let sampleCount = 0;
    for (const value of input.values) {
      if (!Number.isFinite(value)) continue;
      counts[toIndex(value)] += 1;
      sampleCount += 1;
    }
    const denominator = Math.max(1, sampleCount);
    return {
      key: input.key,
      label: input.label,
      color: input.color,
      borderWidth: input.borderWidth,
      y: counts.map((count) => (count / denominator) * 100),
    };
  });

  return { x, series };
}

function percentile(sorted: number[], p: number): number {
  if (sorted.length === 0) return 0;
  const idx = (sorted.length - 1) * p;
  const lo = Math.floor(idx);
  const hi = Math.ceil(idx);
  if (lo === hi) return sorted[lo];
  const t = idx - lo;
  return sorted[lo] * (1 - t) + sorted[hi] * t;
}

function average(values: number[]): number {
  return values.reduce((sum, value) => sum + value, 0) / values.length;
}

/**
 * Pick indices to keep when downsampling an array of length `len` to roughly
 * `target` evenly-spaced points. First and last indices are always kept.
 */
function pickKeepIndices(len: number, target: number): number[] {
  if (len <= target) return Array.from({ length: len }, (_, i) => i);
  const stride = (len - 1) / (target - 1);
  const seen = new Set<number>();
  const keep: number[] = [];
  for (let k = 0; k < target; k++) {
    const idx = Math.round(k * stride);
    if (!seen.has(idx)) {
      seen.add(idx);
      keep.push(idx);
    }
  }
  return keep;
}

function downsampleEtfResult(etf: EtfResult, target: number): EtfResult {
  const idx = pickKeepIndices(etf.dates.length, target);
  return {
    ...etf,
    dates: idx.map((i) => etf.dates[i]),
    dailyValues: idx.map((i) => etf.dailyValues[i]),
    smaPrices:
      etf.smaPrices.length === etf.dates.length
        ? idx.map((i) => etf.smaPrices[i])
        : etf.smaPrices,
  };
}

function downsampleBacktestResult(result: BacktestResult, target: number): BacktestResult {
  const idx = pickKeepIndices(result.dates.length, target);
  return {
    dates: idx.map((i) => result.dates[i]),
    nonLeveragedValues: idx.map((i) => result.nonLeveragedValues[i]),
    investedValues: idx.map((i) => result.investedValues[i]),
    etfResults: result.etfResults.map((etf) => downsampleEtfResult(etf, target)),
  };
}

function getFuturesDefaultStartDate(endDate: string): string {
  const end = new Date(`${endDate}T00:00:00Z`);
  if (!Number.isFinite(end.getTime())) return CONSTANT_SP500_SHORTCUT_DATE;
  end.setUTCFullYear(end.getUTCFullYear() - 20);
  const candidate = end.toISOString().slice(0, 10);
  return candidate < CONSTANT_SP500_SHORTCUT_DATE ? CONSTANT_SP500_SHORTCUT_DATE : candidate;
}

main().catch((err) => {
  console.error("[snapshots] Generation failed:", err);
  process.exit(1);
});
